config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'react-items', to: 'portfolios#react'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
    <div class="inner">
        <p class="app-footer"><%= copyright_generator %></p>
    </div>
</footer>

app/views/shared/_application_nav.html.erb
<nav class="navigation">
    
    <input type="checkbox" id="group1" />
    <label for="group1">
    <ul class="navigation__group first">
        
        <li class="navigation__group-link"><a href="/about-me">Lein Davir<%= nav_helper 'navigation__group-link', 'li' %> </a></li>
        <li class="navigation__group-link"><a><%= login_helper 'navigation__group-link'%></a></li> 
    </ul>
    <span class="toggle">☰</span>
    </label>
</nav>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
    <p> <%= copyright_generator%> </p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<header class="blog-header">
    <div class="container">
        <h1 class="blog-title">My personal blog</h1>
        <p class="lead blog-description">This blog was created as an addon to my portfolio to show case
        the implementation of web sockets with action cable</p>
        
        <span>
            <%= link_to 'New Blog', new_blog_path if logged_in?(:site_admin) %>
        </span>
        <span>
            <%= link_to 'Topics', topics_path %>
        </span>
    </div>
</header>

app/views/shared/_blog_nav.html.erb
<header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-8 pt-1">
            <div class="nav-scroller py-1 mb-2">
                <nav class="nav d-flex justify-content-between">
                    <%= nav_helper 'nav-link', 'span' %>        
                </nav>
            </div>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
               <%= login_helper 'nav-link'%>
        </div>
    </div>
</header>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
    <div class="p-3 mb-3 bg-light rounded">
        <h4 class="font-italic">Sharing in giving</h4>
        <p class="mb-0">Knowledge is powerful only if shared with others.
        This blog aims not only to share information regarding me but also contribute with tips tools and
        tricks for software development.
        </p>
    </div>
        <%= source_helper("alert alert-info") %>
     <div class="p-3">
        <h4>Topics</h4>
        <% @side_bar_topics.each do |topic| %>
            <p><%= link_to topic.title, topic_path(topic)%> </p>
        <% end %>
     </div>


    <div class="p-3">
        <%= render 'shared/social_media' %>
    </div>
</aside>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
    <%= link_to 'Home', root_path %>
    <%= link_to 'About Me', about_me_path %>
    <%= link_to 'Contact', contact_path %>
    <%= link_to 'Blog', blogs_path %>
    <%= link_to 'Portfolio', portfolios_path %> 
</div>

app/views/shared/_new_nav.erb
<!-- Available in two variations: "light" and "dark" | Change <header> class to see impact. -->
<header class="dark">
  <nav role="navigation">
    <a href="javascript:void(0);" class="ic menu">
      <span class="line"></span>
      <span class="line"></span>
      <span class="line"></span>
    </a>
    <a href="javascript:void(0);" class="ic close"></a>
    <ul class="main-nav">
      
      <li class="top-level-link">
        <%= link_to 'Home', root_path %>      
      </li>       
      <li class="top-level-link">
        <%= link_to 'Portfolio', portfolios_path, :class => "mega-menu" %>
        <div class="sub-menu-block">
          <div class="row">
            <div class="col-md-4 col-lg-4 col-sm-4">
              <h2 class="sub-menu-head">Rails</h2>
              <ul class="sub-menu-lists">
                <li><a>Mens</a></li>
                <li><a>Womens</a></li>
                <li><a>Kids</a></li>
                <li><a>New Born</a></li>
                <li><a>View All</a></li>
              </ul>           
            </div>
            <div class="col-md-4 col-lg-4 col-sm-4">
              <h2 class="sub-menu-head">MERN</h2>
              <ul class="sub-menu-lists">
                <li><a>Wallets</a></li>
                <li><a>Athletic bag</a></li>
                <li><a>Backpack</a></li>
                <li><a>Bucket Bag</a></li>
                <li><a>View All</a></li>
              </ul>
            </div>
            <div class="col-md-4 col-lg-4 col-sm-4">
              <h2 class="sub-menu-head">UX/UI</h2>
              <ul class="sub-menu-lists">
                <li><a>FLOAT LAYOUT</a></li>
                <li><a>FLEXBOX</a></li>
                <li><a>GRIDS</a></li>
                <li><a></a></li>
              </ul>
            </div>
          </div>
          
          <div class="row banners-area">
            <div class="col-md-6 col-lg-6 col-sm-6">
              <img src="https://source.unsplash.com/random" width="100%;">
            </div>
            <div class="col-md-6 col-lg-6 col-sm-6">
              <img src="https://source.unsplash.com/random" width="100%;">
            </div>
          </div>
          
        </div>
      </li>
      <li class="top-level-link">
        <a class="mega-menu"><span>Contact</span></a>
        <div class="sub-menu-block">
          <div class="row">
            <div class="col-md-4 col-lg-4 col-sm-4">
              <h2 class="sub-menu-head">About me</h2>
              <ul class="sub-menu-lists">
                <li><a>About</a></li>
                <li><a>Mission</a></li>
                <li><a>Community</a></li>
                <li><a>Team</a></li>
              </ul>           
            </div>
            <div class="col-md-4 col-lg-4 col-sm-4">
              <h2 class="sub-menu-head">Contact</h2>
              <ul class="sub-menu-lists">
                <li><a>News</a></li>
                <li><a>Events</a></li>
                <li><a>Blog</a></li>
              </ul>
            </div>
            <div class="col-md-4 col-lg-4 col-sm-4">
              <h2 class="sub-menu-head">Community talk</h2>
              <ul class="sub-menu-lists">
                <li class="twitter-link"><%= link_to 'Twitter Feed', tech_news_path %></li>
              </ul>
            </div>
          </div>
          
          <div class="row banners-area">
            <div class="col-md-6 col-lg-6 col-sm-6">
              <img src="https://source.unsplash.com/random" width="100%;">
            </div>
            <div class="col-md-6 col-lg-6 col-sm-6">
              <img src="https://source.unsplash.com/random" width="100%;">
            </div>
          </div>
          
        </div>
      </li>
      <li class="top-level-link">
        <a class="mega-menu"><span>Blog</span></a>
        <div class="sub-menu-block">
          <div class="row">
            <div class="col-md-4 col-lg-4 col-sm-4">
              <h2 class="sub-menu-head">Topic 1</h2>
              <ul class="sub-menu-lists">
                <li><a>About</a></li>
                <li><a>Mission</a></li>
                <li><a>Community</a></li>
                <li><a>Team</a></li>
              </ul>           
            </div>
            <div class="col-md-4 col-lg-4 col-sm-4">
              <h2 class="sub-menu-head">Topic 2</h2>
              <ul class="sub-menu-lists">
                <li><a>News</a></li>
                <li><a>Events</a></li>
                <li><a>Blog</a></li>
              </ul>
            </div>
            <div class="col-md-4 col-lg-4 col-sm-4">
              <h2 class="sub-menu-head">topic 3</h2>
              <ul class="sub-menu-lists">
                <li><a>New Opportunities</a></li>
                <li><a>Life @ Company</a></li>
                <li><a>Why Join Us?</a></li>
              </ul>
            </div>
          </div>
          
          <div class="row banners-area">
            <div class="col-md-6 col-lg-6 col-sm-6">
              <img src="https://source.unsplash.com/random" width="100%;">
            </div>
            <div class="col-md-6 col-lg-6 col-sm-6">
              <img src="https://source.unsplash.com/random" width="100%;">
            </div>
          </div>
          
        </div>
      </li>
      <li class="top-level-link">
        <a><span>Contact</span></a>      
      </li>
    </ul> 
  </nav>   
</header>  
  

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
    <div class="container">
    <p class="float-right">
        <%= link_to 'View All Portfolio Items |', portfolios_path %>
        <a href="#">Back to top</a>
    </p>
        <%= copyright_generator%>
    </p>
    </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">My Portfolio</h1>
        <p class="lead text-muted"> These are one of the most exciting projects
        I have worked with, mixing differents technologies and adquiring a ton of knowledge
        while having fun</p>
        <p>
        <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
        <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
        </p>
    </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
    <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
            <h4 class="text-white">About</h4>
            <p class="text-muted">The portfolios elow showcast the technologies and projects
            I usually work with, it combines the Rails Stack and the Mern stack plus some additional
            projects regarding only to computer science</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
            <h4 class="text-white">Explore</h4>
            <ul class="list-unstyled">
            <%= nav_helper 'text-white', 'li' %>
            <li><%= login_helper %></li>
            </ul>
        </div>
        </div>
    </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
        <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>Lein Davir</strong>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    </div>
</header>

app/views/shared/_social_media.html.erb
<h4 class="font-italic">Social Media</h4>
<ol class="list-unstyled social-links">
    <li><a href="https://github.com/davirlein1988" target="_blank"><%= fa_icon "github"%></a></li>
    <li><a href="https://www.facebook.com/lein.davir"target="_blank"><%= fa_icon "facebook"%></a></li>
    <li><a href="https://twitter.com/DAVIRLEIN"target="_blank"><%= fa_icon "twitter"%></a></li>
    <li><a href="https://www.linkedin.com/in/davirlein-prada-6237a1162/"target="_blank"><%= fa_icon "linkedin"%></a></li>
    <li><a href="https://www.instagram.com/leindavir/"target="_blank"><%= fa_icon "instagram"%></a></li>
</ol>